[package]
name = "sosw-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rustfft = { version = "6", features = ["wasm_simd"] }
ndarray = "0.17"
num-complex = { version = "0.4", features = ["std"] }
rand = "0.9"
rand_chacha = "0.9"
crc = "3"
serde = { version = "1", features = ["derive"] }
log = "0.4"
reed-solomon = "0.2"


[dev-dependencies]
serde_json = "1"
